myloglink: "/TXT/mylog.txt"
githublink: "https://github.com/TakeMeGH/os222"
author: "Abdul Rafi"
title: "OS222: Operating Systems 2022-2"
tarballlink: "https://os.vlsm.org/Log/TakeMeGH.tar.bz2.txt"
copyright: "2022"
